DELIMITER ;

DROP PROCEDURE IF EXISTS group_client_generator;

DELIMITER #

CREATE PROCEDURE group_client_generator()

BEGIN

DROP TABLE IF EXISTS CLIENT_ACTIVE_LOAN_STATUS;
DROP TABLE IF EXISTS CLIENT_CLOSED_LOAN_STATUS;
DROP TABLE IF EXISTS ATTENDANCE_BY_CLIENT;
DROP TABLE IF EXISTS ATTENDANCE_BY_CLIENT_DIV;


call client_generator();


END#

DELIMITER ;